name: FruchtJobs
version: ${project.version}
main: com.gestankbratwurst.fruchtjobs.FruchtJobs
api-version: 1.13
depend: [FruchtCore, Vault]
authors: [Gestankbratwurst]
description: Jobs plugin für FruchtLabor
